### ISSUE TITLE
[Request] "N" key can close the "Save Changes" Dialog

### ISSUE THREAD

**Issue by chiminirc** [rgriebl/brickstore#127]
When closing multiple documents it would allow me to do so faster.
Today the icons are "Save", "Discard", "Cancel"

Requesting "Save" "Do**n**'t Save" "Cancel"

**Comment by rgriebl** [comment]
This depends on your platform: Microsoft calls the don't-save-action "Discard" and it does not want any shortcuts on an destructive actions, so you don't get one on Windows.
Apple on the other hand calls it "Don't Save" and allows the shortcut `Command+Delete` to trigger destructive actions.
BrickStore is maintainable on 3 platforms right now, because - thanks to Qt - I don't have to deal with all the subtleties of the individual platforms and I'm going to keep it this way.
So sorry - no can do.

The workaround is to use `Right` + `Space`

**Comment by chiminirc** [comment]
I was hoping the compiler took care of this on it's own.  Sort of provide a designator and let the compiler sort out what happens in the build.  I ask because in brickstock this seems to work without the need to "ALT + N". Just pressing "N" would work so I figured maybe it's in the code somewhere.  Maybe the new build engine doesn't construct that. 

![image](https://user-images.githubusercontent.com/76887746/105741693-3ba15680-5f00-11eb-8c34-d92e8c8607f9.png)

**Comment by chiminirc** [comment]
I use notepad++ a lot so it stems from use in there.  Maybe it's actually a canned "YES,NO,CANCEL" dialog that is invoked instead of custom button label dialog.
![image](https://user-images.githubusercontent.com/76887746/105742034-9f2b8400-5f00-11eb-83fa-544f6d2c1b1d.png)
