### ISSUE TITLE
ECB Popup

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#134]
I didn't shut down my PC last night, and this morning I opened it had this popup:

I suppose it disconnected from Wifi and BS tried to download the Exchange Rate.

<img width="256" alt="Captura de pantalla 2021-01-27 105116" src="https://user-images.githubusercontent.com/1063368/105974005-b481e900-608d-11eb-96bf-caff3cfdaea7.png">

Maybe if there is no internet connection, just wait until there is to try the download? So this Popup only appears when you manually want to update it and you are disconnected, but not by itself at the daily download setting it has?

**Comment by rgriebl** [comment]
What is this "no internet" you're talking about? ;)

**Comment by ZZJHONS** [comment]
Oh, okay, just happened this morning, the other days I hadn't left BS open.

Then this is closed for now?

**Comment by ZZJHONS** [comment]
Just appeared the Popup again, I was browsing BL for 20 mins and then went to open BS and it appeared.

<img width="274" alt="Captura de pantalla 2021-02-04 115042" src="https://user-images.githubusercontent.com/1063368/106882692-571a1780-66df-11eb-83fc-5f025e4e5943.png">

**Comment by rgriebl** [comment]
Well - I left the first check on startup to be verbose, so you know that you don't have the latest rates. Only the background checks that'll happen every 4 hours after that are set to silent, because we know that we got a valid rate at least once when we started (or if we didn't, the user has been made aware of the situation).
That being said: "Host not found" means something broken with your internet connection - it couldn't even resolve the ECB's hostname.
