### ISSUE TITLE
Parting out item with 0 qty only works for current document.

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#138]
If you try to part out an item with qty 0 in a file only works if it is parted out in the same file, it is deleted and its inventory imported with qty 0. But if you say no, no new document is created with the inventory and 0 qty.

Also from the part out window, if you put 0 in the part out number it creates a new file but with the last part out qty used with that window.

**Comment by paramecie** [comment]
You simply cannot enter 0 here (as of now):

![image](https://user-images.githubusercontent.com/32078594/106015942-448c5680-60bf-11eb-9922-3a9faa1153af.png)

**Comment by ZZJHONS** [comment]
You can write in it, but it uses the previous value.

**Comment by paramecie** [comment]
Yes, that's what I meant; it doesn't allow a zero.

**Comment by rgriebl** [comment]
I can't stop you from hitting the zero key in an empty edit fields, because you might be writing '10' in a weird way. I will however validate the input as soon as you leave the edit field (TAB, mouse click anywhere else) to be a positive number.
As for parting out 0-qty items: there are two options:

1. I'll disable the command in this case
2. I'll ask the user for a qty != 0 and default the answer to 1

Opinions?

**Comment by paramecie** [comment]
The question is: what would someone do with a list with zero quantity?

If there's no use, then simply disallow it (don't accept "0" when the field is empty, or as a first char anyway...)

If there's an use to it, then you should accept it.
I never used a zeroed list, but I can see womeone would like either:

* to set to zero so he knows he has to define (count) the quantity later on...

* or set to zero in order to later on use this file as an Add Items "merge source" so he can apply the Remarks or Prices for example, but not changing the quantities of the original file...

That could be useful I think.

Of course that just give #68 much more pressure :-)
