### ISSUE TITLE
Add timestamp to log

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#142]
I saw these warnings now but don't know when exactly happened:

<img width="814" alt="Captura de pantalla 2021-01-27 192007" src="https://user-images.githubusercontent.com/1063368/106035695-b327df00-60d4-11eb-9323-849ec2547e20.png">

**Comment by paramecie** [comment]
Around 15:20 Paris Time I had problems.

Many report problems, like:
https://www.bricklink.com/message.asp?ID=1248644
https://www.bricklink.com/message.asp?ID=1248659

I just hope people are acting responsibly with BrickLink load.

Otherwise one of these days they may decide to strenghten the rules and limit all eventual "bots" (understand, any business tools) to even less than 5000 queries, which is easier and cheaper than making their system more robust.

**Comment by ZZJHONS** [comment]
I suppose it had something to do with BL up and down, that's why the issue is just a suggestion to add the timestamp and not about the errors per se.

They got it under control lately this past year compared to before... so let's hope things are getting better.

About the API limit, it is already pretty strict for some big sellers... The other marketplace has a 600 limit per minute in API requests.

https://www.brickowl.com/api_docs

**Comment by paramecie** [comment]
Yep yep read you, and understood your suggestion, and agree.

But BrickLink is different, and they can decide they're far too generous :-(

See the current "Incomplete Minifig" problems.

Instead of BEFORE sending an e-mail or contact the seller through the message system (and fix it?) - they simply remove the items from the shops FIRST.

**Comment by ZZJHONS** [comment]
Don't get me started in how many things BL can do without spending any extra resources...

**Comment by rgriebl** [comment]
> I saw these warnings now but don't know when exactly happened:

The libpng warnings are totally harmless, but I cannot suppress them. It just means that the PNG file is quite old.
Also the "image download failed" is to be expected: that happens every time you select an item/color combination for which BL does not have a normal picture. I cannot distinguish those from real errors, so I log them anyway.

I thought about timestamps, but they aren't really needed and clutter the log quite a bit.

Take the whole log thingy with a grain of salt ... I added this mainly for easier script debugging in the future.
