### ISSUE TITLE
Database Update - auto update not working?

### ISSUE THREAD

**Issue by legobanker** [rgriebl/brickstore#148]
On previous builds, the BS would auto update the BrickLink DB file.  Did build 244 take away that function?  I did a manual update for it to work?

**Comment by paramecie** [comment]
?

![image](https://user-images.githubusercontent.com/32078594/106097371-78a35e00-6137-11eb-9786-e0a65aea0333.png)

**Comment by legobanker** [comment]
I can't remember the build, but at one point upon opening BS it was automatically updating.  It was the first thing you saw before it opened the main window.  I'm going to check my settings now and see what it says

**Comment by legobanker** [comment]
Here's mine:

![image](https://user-images.githubusercontent.com/77599267/106219999-8ba24680-61a8-11eb-8f17-cf9c64522149.png)

**Comment by paramecie** [comment]
Yes it happened due to a database format change.
But in short, no it doesn't update before the "older than" delay.

BTW - 2 days is mucho short, for the database and much more for BrickLink.
I'd recommend having a longer delay - like a week - and if you really need it for some important list, do force the refresh.
Anyway - IMO.

**Comment by rgriebl** [comment]
Just to clarify: the stress is only on my server in this case. So while a 2 day interval is a bit excessive, my server has no problems dealing with it nowadays.
