### ISSUE TITLE
How to copy the price information of the same part in document A to document B (including the graded price)

### ISSUE THREAD

**Issue by csmsc711** [rgriebl/brickstore#230]
Hi there.
How to copy the price information of the same part in document A to document B (including the graded price).
Thanks.

**Comment by paramecie** [comment]
Hi!

I don't know if others have an idea about this.

How I would do this, at a first glance?
Right now there a bug in Consolidation, thus I can't show how it works.
#233 

But it would consist to:
* open your file with the good prices (your document A)
* select the items you wish
* temporarily change the quantity of those items you wish to apply the prices to zero "0" (right click, qty, set)
* copy (ctrl+c) this
Now go to the file you wish to update, don't select anything, paste (ctrl+v)

With the consolidation it should permit you to overwrite the old prices with the new ones.
Again, as of right now, it seems there's a little bug, it'll be fixed quickly I'm sure.

The quantity set to zero trick is to overwrite prices etc, but NOT the quantities, they won't change because you're adding 0 ;-)

**Comment by csmsc711** [comment]
Yes,I did the same operation as you said before, but I felt a little troublesome.
I used BrickStock before and it has the option to copy other documents directly to this document under the edit menu.
Thank you anyway！

**Comment by rgriebl** [comment]
I thought I had merged in that functionality, but it seems like I didn't. Then again, it makes more sense to have a generic *copy fields from other document* function instead of yet another copy-xyz

**Comment by paramecie** [comment]
> a generic _copy fields from other document_

Oh yes!
