### ISSUE TITLE
Question regarding "spread cost amount"

### ISSUE THREAD

**Issue by legobanker** [rgriebl/brickstore#231]
I've been working with some PAB inventory and the "spread cost amount".  I was coming up with different costs for the parts (based on the number of parts across three different part type).  So I decided to do a random test.  Below are two different tiles, both with equal amounts.  I spread the cost of $17.189 (or $17.19) over 1,000 parts.  As you can see, the cost per part is different.  My question is this:  What is the formula for the cost per part and how is it derived?  Is it based on weight, color, type?

If I have the same amount of parts for each type (say two tiles), shouldn't the cost per part be the same for both?  I originally thought it was spread over the percentage of parts in a set, sort of a weighted cost?

![image](https://user-images.githubusercontent.com/77599267/108579363-855d4100-72f4-11eb-8570-4748d12baa6f.png)

**Comment by paramecie** [comment]
It's proportional to the Price of course!

Try this:
* import any Set
* select all, apply an average price for example
* the total price is now your reference (say 200$)
* then spread your cost based on which price you bought it, example: 100$
* it then will put as cost a proportion based on the price of each lot
* in the end, if you select all, your total cost will be 100$
And here, normally, each lot cost should be 1/2 the average price because you paid the whole 50% of its total average price.

**Comment by paramecie** [comment]
The total price of this (example) is 30$

![image](https://user-images.githubusercontent.com/32078594/108582533-451db300-7334-11eb-9c15-17c5e2037279.png)

But I paid it (lucky me) 15$, which I set when spreading the cost.

The cost of each lot is now 1/2 based on the price.
