### ISSUE TITLE
Critical, Consolidation is still erroneous

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#278]
Build 337, whatever the sort order is :-(

Same steps as #277 - for 3 lots, COPY:

![image](https://user-images.githubusercontent.com/32078594/110061040-232a2480-7d67-11eb-86c9-9819737ad00d.png)

PASTE here, having no selection (don't overwrite):

![image](https://user-images.githubusercontent.com/32078594/110061102-3fc65c80-7d67-11eb-8b7d-cd7e5cca49e5.png)

Consolidation, select "New item" and "Yes to all":

![image](https://user-images.githubusercontent.com/32078594/110061198-769c7280-7d67-11eb-8b40-8ad208a6b21b.png)

**Wrong, the first price has the OLD value, and the next prices have the New value.**

It seems to me that BS is taking BOTH:
* the invalid default choice for the **first value**
* and the good values of choice "New Item" and "Yes to All" for the **next 2 values**.

This explains why the first is different.

![image](https://user-images.githubusercontent.com/32078594/110061491-f9bdc880-7d67-11eb-995b-4644c1606dca.png)

Please carefully check Consolidation, it's business critical.
Please.

**Comment by rgriebl** [comment]
That's what i meant with "oddities" in my last comment. This dialog needs to be split up:

The "Yes To All" actually applies to everything AFTER the current merge. The current merge has to be done manually using the list at the top. 
And yes - this is odd. I'm thinking about splitting this up into 2 steps (first: choose manual / automatic, then: if manual go through each merge), but not for this release. Otherwise it will never happen.

What I can do for now, is that "Yes To All" ignores whatever you chose in the list and applies "prefer" settings also to the current merge.

**Comment by paramecie** [comment]
Mmmmh - Yes to All means, to all.
Not all after this one :-)

I don't understand how it could be different than YES TO ALL (whatever you do before?)

**Comment by paramecie** [comment]
Build 339: works far better; thank you! I'm testing...

**Comment by paramecie** [comment]
Still checking. For now apart remarks I don't see any failure.
