### ISSUE TITLE
Add a toggle capability to include "Lot ID" when exporting to BrickLink XML

### ISSUE THREAD

**Issue by thx11380** [rgriebl/brickstore#289]
Please add a toggle capability to include "Lot ID" (or any other required field to make mass update/upload work) when exporting via BrickLink XML.  I don't set my prices by using either last 6 month sales' or current inventory's average price or qty average price.  Once I update my prices in the XML file, the file can't be mass updated/uploaded to BrickLink because the "Lot ID" field (or any other required field to make mass update/upload work) is missing.

**Comment by paramecie** [comment]
Note that the ID is not used or necessary to mass UPLOAD.

Note also there's a new copy feature you could use (at lease temporarily).

* import your shop
* set your prices on your software
* open the XML in BrickStore and copy the XML prices to your shop inventories
* mass update

**Comment by rgriebl** [comment]
There really is no single "BrickLink XML", but a lot of similiar XML schemas used for uploading and downloading different things to and from BrickLink: Mass-Upload, Mass-Update, InvReq, WantedList, Orders, etc.
That being said, the menu option "Export BrickLink XML..." really should be called "Export BrickLink Mass-Upload XML...", but these are the things that you just overlook completely after looking at them for 17 years ;)
But that also means that I can't simply add the LotId to the BrickLink XML export because that would break its primary use-case: Mass-Upload.
I have no idea what software you are using to set your prices, but if you would instead edit the `Price` tags in the BSX file directly (while also generating `DifferenceBaseValues` `Price` attributes for the old prices), you could directly use this file in BrickStore to generate a minimal Mass-Update.

**Comment by rgriebl** [comment]
Closing as there was no more feedback. I won't change the current implementation as this works for all standard use cases. Plus there's workaround mentioned in the preceding comment.
