### ISSUE TITLE
'Show in my store' still not working for sets

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#327]
Some problems with 'Show in my store' were fixed a while back but still two issues remain.

Collectable minifigure sets are listed on Bricklink by name but Brickstore looks for them by set number so they are never found.

Other sets are listed on Bricklink with the short set number (e.g. 3221) but Brickstore searches for the full set number (e.g. 3221-1) again the sets are never found.

**Comment by rgriebl** [comment]
@paramecie You said that your "special" store inventory link works perfectly fine and I trusted you ;)

**Comment by paramecie** [comment]
@rgriebl It's not my fault if they're bad devs in this team!
Na, never tried with Sets or cols things - I'm sure you'll find a solution :-)

**Comment by paramecie** [comment]
I've tried a bit for **Collectible Minifigures Series**.

If you search (assuming you've one in stock):
![image](https://user-images.githubusercontent.com/32078594/113152626-99bb2480-9236-11eb-8bf8-963770d6b4d8.png)

I confirm, this link doesn't work:
https://www.bricklink.com/inventory_detail.asp?catType=S&q=col14-16

One solution would be to make a specific search for them:
* if it's a Set
* if it belongs to the Category "Collectible Minifigures"
* then search by its full name, example col14-16 => Spider Lady, Series 14 (Complete Set with Stand and Accessories)

The search link would then be:
https://www.bricklink.com/inventory_detail.asp?q=spider%20lady [etc, should be full name but I simplified this example]

Full name is recommended as otherwise if we do a partial search on some simple names like "Joker" we could find other results...
