### ISSUE TITLE
Search by color

### ISSUE THREAD

**Issue by landerr9290** [rgriebl/brickstore#346]
Hi, first off sorry if this isn't what this is for, I don't really use github.  I'm trying to search for parts with a specific color and am not sure if it's possible.  I included a photo as an example.  I'm currently trying to search for light nougat "female" minifig heads but am unable to filter by color.  If this isn't a feature already I think it would be very useful.

**Comment by rgriebl** [comment]
Yes - that feature would be helpful, especially since the known colors database has gotten better now.
I made quick prototype today, so I know it works in theory. The biggest problem is now to find a way to make it easy to use in the UI, because you can have a recursive dependency between items and colors (read: my first attempt was a usability nightmare ;) )

**Comment by rgriebl** [comment]
Build 442 (https://github.com/rgriebl/brickstore/actions/runs/824151120) has a first implementation of this feature: click the "lock" icon on the top right in the `Add Item` dialog.
Please give a test drive and let me know how it works.
