### ISSUE TITLE
Ctrl+A scrolls to the top of the document automatically

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#388]
I don't know if this is intended, but why it scrolls to the top instead of staying where you are?

**Comment by rgriebl** [comment]
This is a side effect of 2ead74849efa94b0f972511fc996dbe813c1a83c which was implemented to always keep the current item (the one with keyboard focus) visible while filtering, sorting, etc.
It just scrolls to the top if you never clicked anywhere in a new document, because the current item starts out at row 1, column 1.

It's next to impossible to cleanly implement "select all" in a different way due to the selection update optimizations. I guess you'll have to live with the current behavior for now :)

**Comment by ZZJHONS** [comment]
Oh, so it scrolls to the part selected, okay, then I just have to click the part I'm viewing to stay there, that would work. Thanks!

PD: Tested and working.
