### ISSUE TITLE
Match Items against Set Inventories... fails silently

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#40]
Not sure what it's supposed to do, and guessing you know about this, but as a reminder - this doesn't do anything.

![image](https://user-images.githubusercontent.com/32078594/103802142-fdc2b800-504e-11eb-8e00-df6b6046e6d6.png)

**Comment by chiminirc** [comment]
I was wondering the same.

**Comment by rgriebl** [comment]
Yes - that's a completely new feature: played around with the [Knapsack problem](https://en.wikipedia.org/wiki/Knapsack_problem) and it's still missing an UI. I should probably hide it from the menu in the meantime.

BTW: I had to trash the original recursive implementation, because BL has too many items nowadays to fit the number of required recursions on a standard Windows' process stack ;)

**Comment by paramecie** [comment]
That's an HOT subject :-) Maybe some tree with removing / aggregating a maximum of branches you can, so it doesn't go wild down the stack... Good luck with this!
