### ISSUE TITLE
Last 6 months Sales and Current Inventory Qty columns

### ISSUE THREAD

**Issue by istaylor92** [rgriebl/brickstore#428]
Is it possible to make a columns populated with the 
Last 6 Months Sales Qty Sold, 
lots Sold, 
Current inventory Qty, 
and Current lots Qty.
From the price guide that is usually on the left. 
Utilizing the ratio of current inventory to last 6 months sales is important to me. and having them in columns would be super useful.

**Comment by InterruptSpeed** [comment]
> I've brought this up in the past and it was passed on. I just wanted to 2nd it as I would find it very useful.

possible to link to the issue from the past for some context?

**Comment by InterruptSpeed** [comment]
I have [some changes](https://github.com/InterruptSpeed/brickstore/tree/feature/qty_sales_ratio) that I feel representative of the ask here. The approach involves 5 columns which are populated with values based on the lot condition of the row after Ctrl+A Ctrl+G is invoked. I saw in a previous thread new columns might not be preferred and so rather than put in a pull request I'll leave it where it is now until I talk with @rgriebl.
![Screen Shot 2021-10-14 at 11 17 40 AM](https://user-images.githubusercontent.com/23084704/137347430-717e9a16-b0fe-47ae-bc00-f6bf7838828e.png)

**Comment by chiminirc** [comment]
@InterruptSpeed - I don't suppose you do a build for Windows and make it available for download?

**Comment by InterruptSpeed** [comment]
lemme see what I can do...have a Windows machine here somewhere. I'd rather discuss with @rgriebl though b/c I don't want to breach any protocols...not sure its my place to fork something and offer a release...the purpose of the fork is to add a feature and submit a pull request to the official project.

**Comment by Mr-P1nky** [comment]
I would like to second this. i think a ratio of 6 months sold vs current inventory would help me out alot with pricing

**Comment by chiminirc** [comment]
> @InterruptSpeed - I don't suppose you do a build for Windows and make it available for download?

The script?  I'd have to dig it up.  I haven't used it in a while and did it in powershell.  The difficult part is having to pull down recent priceguides so i was using the other brickstock app which could pull in more priceguide data via grouped requests.

**Comment by rgriebl** [comment]
I've now created a super-task issue for custom columns: #617

I will close this issue here however, as it will not be implemented in BrickStore itself and just sitting around in the bug tracker as an open bug for years doesn't help anyone.
