### ISSUE TITLE
Spread Cost Amount - price vs. weight

### ISSUE THREAD

**Issue by BrickSouth** [rgriebl/brickstore#455]
I'm probably being way too picky here, but something that has always bothered me as a seller of used Lego is how spreading the cost amount is based on the price of each lot rather than the weight. Since nearly all used Lego is sold by the weight the more accurate way to spread the cost would be the weight of each lot. That tiny little rare part that weighs 0.001 of an ounce technically cost you a very small sliver of your overall cost. Whereas it is showing up as your biggest cost because the value is so high. I realize it probably doesn't matter in the long run, but just something that has bugged me and I'm wondering if anyone else has thought about this.

**Comment by Huseriato** [comment]
Im supporting this. Our target price is a fixed price per 100g (because this is the price we can sell used parts locally). So selling a part over bricklink does only make sense, if the price is higher than our local fixed price. We'll need an option to apply the average price, but only if it is higher than our fixed price per 100g (which should be used else). Currently we're adjusting those prices manually, which is very annoying. So any change to make this easier is welcome.
