### ISSUE TITLE
Sometimes Supr key doesn't work

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#476]
Happened a few times in the latest builds, sometimes the Supr key does nothing.

I don't know exactly how to replicate. Yesterday opened BS, with a file, then CTRL+I, CTRL+I to import a set Inv and it didn't let me use the key neither in the file nor in the inventory imported.

Today just opened a file, added a part and it doesn't let me delete anything using just the key. The rest of the fields respond okay.

Okay I think I just found out:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/1063368/145800133-d0e2f9a6-6cf7-4aa6-9995-28ba924ba581.png">

Its a problem with some translations, its missing the shortcut.

**Comment by rgriebl** [comment]
The problem is that in both `fr` and `es` the shortcut for the `Del` key was translated `Sup` or `Supprimer`.
That's not how it's supposed to work though, even if it's a bit counter-intuitive: https://doc.qt.io/qt-5/linguist-translators.html#changing-keyboard-accelerators

Shortcut translations are always to **english** and they should only be different from the default, English text, if the shortcut key doesn't make sense in the target language.

As an hypothetical example, let's change the printing shortcut `Ctrl+P` for German, because printing is called "Drucken" over here: the translation in Linguist would be `Ctrl+D`, but the menu would automatically show this fully translated as `Strg+D` (but then again, in the real world, it's still `Ctrl+P` even in German ;) )

I'll go through all the ts files and fix what I can find.

**Comment by ZZJHONS** [comment]
Okay, that is what seemed, I wasn't sure if the translation file was just the name of the key shortcut or the actual shortcut used.

**Comment by rgriebl** [comment]
Fixed
