### ISSUE TITLE
Unable to copy Lot ID

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#540]
Right click the Lot ID and selecting copy it just copies the item ID.

You can't double click the Lot ID field either to select it to copy the content.

**Comment by paramecie** [comment]
Yes, it was a long time ago... but here no problem to copy with the right click option either double click and copy...

Is it still a valid issue?
Other wise Robert could close it?

**Comment by ZZJHONS** [comment]
@paramecie you sure? Just tried again and it still doesn't work for me, nether copy the lot from the imported store to a file and trying to copy the Lot Id there either.

**Comment by paramecie** [comment]
Ah, you're right, sorry **LOT** ID :-(

Agreed, on legacy version I can't Copy the LOT ID.

When you Copy it shows Item ID (if you Paste), but in  reality it copies the whole Lot line.
Same thing when you Cut, it cuts the Lot.

I think the problem comes from the fact that as Lot ID isn't editable (it could be but locked), then Copy/Cut simply use the whole Lot line.

For now one way to copy is to right click, Create a filter from selection, then you can copy the Lot ID from the Filter Expression field.

**Comment by rgriebl** [comment]
I have a fix for that already (copy and  clear lot id). I just need to stabilize the new Qt6 release first.
