### ISSUE TITLE
Suggestion: Partout sets in set

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#593]
Just like the option in BL add a checbox to partout the sets inside a set inventory without the need to tell BS to partout the list and having to accept 24 popups:

<img width="918" alt="image" src="https://user-images.githubusercontent.com/1063368/190615770-8a3d6793-67d7-47be-b574-e42ef554c92a.png">
<img width="621" alt="image" src="https://user-images.githubusercontent.com/1063368/190615878-a272d878-d48f-4562-9137-fb747c7d138f.png">

**Comment by paramecie** [comment]
Not only Sets? It could work also for Minifigures inside a Set inventory for example.

Or in short, every lot which displays "Inv" in the bottom right corner...

**Comment by xaraxarax** [comment]
or additionaly part out many selected sets at once in one or individual documents

**Comment by rgriebl** [comment]
Could you please test the new part-out options in this build: https://github.com/rgriebl/brickstore/actions/runs/3464052316
It seems to work fine in my tests, but the code is getting quite complex now with the recursions into sets and minifigs.

**Comment by xaraxarax** [comment]
II took 7904-1 as a test object. I would have expected the dialog to come up directly when outpart any set and the option to unpack all subsets would be selectable. if several sets are selected, the option is there, but cannot be selected.

This is the Way: New document, add set 7904-1, part out -> no dialog with options, select one or more parted out subset, options dialog show up ...

https://user-images.githubusercontent.com/79638214/201777731-904db967-501a-4b59-8158-3e950fbe54f4.mp4

Another issue: if i close the add dialog, the main window resizes and centers (Windows 11)

https://user-images.githubusercontent.com/79638214/201776861-27e4165e-7b1c-4fb3-acd2-b4115ac4dea6.mp4

**Comment by rgriebl** [comment]
> This is the Way: New document, add set 7904-1, part out -> no dialog with options, select one or more parted out subset, options dialog show up ...

The part-out from list uses a check if an inventory is "simple" (no alternates, no counter parts), because people complained about an "annoying" dialog popping up there...

But why would you do it this way, instead of using the Import Inventory Dialog (`Ctrl+I, Ctrl+I`) that's specifically tailored to the purpose of importing sets?

**Comment by rgriebl** [comment]
The resize thing is funny: I can even reproduce it in Windows 10, but I have no idea (yet) what causes it :)
Please open a separate bug report for such issues in the future, otherwise I can't keep track of things.

**Comment by rgriebl** [comment]
This build here https://github.com/rgriebl/brickstore/actions/runs/3465927221 only skips the add inventory dialog, when the inventory is REALLY simple (e.g. parting out a minifig)

**Comment by xaraxarax** [comment]
> > This is the Way: New document, add set 7904-1, part out -> no dialog with options, select one or more parted out subset, options dialog show up ...
> 
> The part-out from list uses a check if an inventory is "simple" (no alternates, no counter parts), because people complained about an "annoying" dialog popping up there...
> 
> But why would you do it this way, instead of using the Import Inventory Dialog (`Ctrl+I, Ctrl+I`) that's specifically tailored to the purpose of importing sets?

I am currently only offer parts, but have also all sets in the BL Inventory, only on hold and there are many reasons why, mainly because my tax office wants a stock list with all costs (sets, parts etc) for every fiscal year and to keep things simple. Usually I load my inventory from BL, part out any set in a new document, correct the amount and update in BL. With the part-out I do as usual, corrections, add storage box codes and upload. Long story short, I never used the Import Inventory Dialog in my workflow. 

But maybe that can be easily implemented without annoying most users. e.g. if shift is pressed while the set is parted out, the advanced options will be opened ...

**Comment by xaraxarax** [comment]
> This build here https://github.com/rgriebl/brickstore/actions/runs/3465927221 only skips the add inventory dialog, when the inventory is REALLY simple (e.g. parting out a minifig)

tested and found perfect for me :)

But if it annoys others, a hidden key solution would also be conceivable...
