### ISSUE TITLE
2022.9.3 freezing when opening

### ISSUE THREAD

**Issue by reni3008** [rgriebl/brickstore#604]
Hi
I've just updated to 2022.9.3 and Brickstore no longer works. It loads the GUI, but after it freezes, you can't click anything. Have to kill it via task manager

**Comment by rgriebl** [comment]
That's tough to diagnose. Please uninstall the new version first (via `Settings` > `Add or Remove Programs`) and reinstall the old 2022.4.1 (installing the old one over the new one is not recommended because of changes to the installation locations). 
Then start the old one, go to `Help` > `System Information`, click `Copy to clipboard` and paste that information here as a comment.

**Comment by reni3008** [comment]
Hi, thanks for the quick reply. I've uninstalled and installed old and here is the requested information:

### BrickStore 2022.4.1 (build: 663)

* **brickstore.ldraw**: 31 Mar 2022
* **brickstore.locale**: de
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930141)
* **build.date**: 2022-04-01T23:02:53.000
* **build.host**: fv-az28-463
* **build.number**: 663
* **build.qt.version**: 5.15.2
* **hw.cpu**: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: NVIDIA GeForce GTX 1070 Ti
* **hw.memory.gb**: 63.9
* **os.arch**: x86_64
* **os.name**: Windows 10 Version 2009
* **qt.debug**: false
* **qt.version**: 5.15.2

**Comment by rgriebl** [comment]
Do you have any Anti-Virus/Firewall software that might block the BrickStore procress from downloading its database?
2022.9.x is installed to a different locations (`Program Files` vs. `Program Files (x86)` before), so any custom exception rule you would have created in the past doesn't apply anymore.

**Comment by BobFlip** [comment]
I've been having a similar problem to this. Since getting an SSD drive, OSX boots so fast that if Brickstore was open when I shut the computer down, on startup it loads and tries to download the database before the internet has connected.

There was another time where I'd booted without my data drive connected, and as the files that were open were no longer accessible, Brickstore brought up an error message but I was unable to close it and continue.

**Comment by rgriebl** [comment]
> I've been having a similar problem to this. Since getting an SSD drive, OSX boots so fast that if Brickstore was open when I shut the computer down, on startup it loads and tries to download the database before the internet has connected.

This shouldn't be a problem, since having no internet connection is a normal error condition. BrickStore shouldn't completely freeze in that case (maybe for 30sec max, depending on macOS' network stack), but come up with an error message. BrickStore will then just use the "old" database instead and you can manually update if you need to.

> There was another time where I'd booted without my data drive connected, and as the files that were open were no longer accessible, Brickstore brought up an error message but I was unable to close it and continue.

This is a known (and weird) issue with modal message boxes on macOS that was fixed somewhere between 2022.4.1 and 2022.9.3. Please open a new bug report if you still run into this with 2022.9.3

**Comment by BobFlip** [comment]
Hmmm, not sure about the first then. If I recall right the error message comes up but it won't close when I click it. Turns out I'm still on 2022.4.1, so maybe that's the same error as the second part. I'll update and continue the research!

**Comment by rgriebl** [comment]
@reni3008 did you check your Anti-Virus/Firewall settings?

**Comment by rgriebl** [comment]
Closing for now, as there was no further feedback. Please re-open if it happens again even with disabled Firewall/Anti-Virus.
