### ISSUE TITLE
2022.9.3 isn't launching on Debian

### ISSUE THREAD

**Issue by jJit0** [rgriebl/brickstore#609]
Hi,

When I updated brickstore to the latest version ` Debian-12-Backend-brickstore_2022.9.3_amd64.deb ` the app won't launch
I just have a help menu
```
Usage: /usr/bin/brickstore [options]

Options:
  -h, --help          Displays help on commandline options.
  --help-all          Displays help including Qt specific options.
  -v, --version       Displays version information.
  --rebuild-database  Rebuild the BrickLink database (required).
  --skip-download     Do not download the BrickLink XML database export
                      (optional).
```
I tried both `--skip-download` and `--rebuild-database` but nothing happens! any ideas ?

**Comment by rgriebl** [comment]
You downloaded the `Backend`, which is the command line utility to rebuild the database. Nobody else besides me should have a need for that one.
There is no desktop version, because Debian 11 aka stable aka bullseye does not have qt6 packages. Just noticed that there's a Qt 6.3.1 in the backports repo, so I guess I'll create a Debian Desktop package for the next release.
In the meantime you can try to either install the Ubuntu one (after enabling bullseye-backports) or you use the AppImage (which works on any Linux distro).
See also: https://github.com/rgriebl/brickstore/wiki/Installation-Instructions#linux
