### ISSUE TITLE
lag when filtering

### ISSUE THREAD

**Issue by newfie675** [rgriebl/brickstore#648]
I don't know if anyone else is experiencing this but since the last update the search feature is extremely slow. Files that I have been using for months now take minutes to filter the results. I tried rebooting brickstore with no change in behaviour. Not a big issue but thought I would report it anyway
Thanks
Chris

**Comment by rgriebl** [comment]
If you're on a Mac, then it's fixed already (see #641) and will be part of the next release.

**Comment by artur1231** [comment]
Hi, it's still not fixed. It loads extremely slow. Macbook Pro 15" Intel I7. 
Latest version of BrickStore.

**Comment by rgriebl** [comment]
Which build number are you testing exactly?
Also, could you please tell me the locale macOS is using? (language and country)

**Comment by artur1231** [comment]
Build 890, Ventura 13.2.
Deutsch und Deutschland :)

**Comment by rgriebl** [comment]
890 is the latest official 2022.11.1 release. The bug was fixed since then, but you need to run a development version to get the fix right now (I'm working on a new release, but I can't promise a release date yet)
Go to the **Actions** tab here on GitHub, pick the latest build (should be 929 at the moment) and scroll down to the downloads section. Install as usual.

**Comment by artur1231** [comment]
Perfect, it works fine now! Thanks a lot!

**Comment by newfie675** [comment]
2022.11.2 build 890
12.6 monterey. Canada english
Thanks for the update
