### ISSUE TITLE
Price guide is slow for individual items

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#669]
The new API works extremely well when downloading price data for large inventories but is not so good for individual items.

For example, if I select an item in the insert dialog there is a long delay before the price guide data appears. I've re-installed the previous release to compare and I don't think it's my imagination. It's not a massive difference but it's just feels like it's slowing down my workflow.

**Comment by rgriebl** [comment]
There IS a delay, because I need to be able to batch multiple requests. Right now, I have set this to 0.5 sec, but I can probably lower this.
The other thing is that the new version cannot use the old cache, so everything has to be re-downloaded at least once to get it into the new cache. As soon as you have accessed a price-guide, it should load immediately the next time (just like with the old BrickStore version)

**Comment by SteveTheBrick** [comment]
Ok, thanks for the explanation. I'll live with it for a while and see if the cache-ing makes a difference.
