### ISSUE TITLE
Can build

### ISSUE THREAD

**Issue by TGS-Brick** [rgriebl/brickstore#682]
Thanks again for this piece of software.
I asked a question of the "can build" feature to include the minifigures.
You sent back a piece of code, I can see in downloaded files that the code has been changed to include this, does that mean it will be aviable in the next release, or do I have to compile the code myself, which I'm not wise enough to do:-)

**Comment by rgriebl** [comment]
If you don't want to compile yourself, you have 2 options:
1) wait for the next release (which in this case should hopefully be soon-ish, since I need to fix a serious flaw in the order import logic)
2) install a development version. Pros: you get the latest bug-fixed and features, Cons: those features might not be 100% stable yet :)

To get dev versions, click on the `Actions` above, pick the first build with a green checkmark, then scroll down and download the build for your platform. Install as usual (or see the `Wiki` for the installation instructions.
