### ISSUE TITLE
Antivirus quarantine Brickstore

### ISSUE THREAD

**Issue by gualandd** [rgriebl/brickstore#684]
The antivirus put .exe in quarantine for "Unauthorized file encryption" issue.
Brickstore can no  more be used in this version for me, no problem with older versions

**Comment by rgriebl** [comment]
Whatever you download here from GitHub is clean. If you don't trust me or GitHub, check BrickStore.exe on https://www.virustotal.com (which I just did, both the installer and BrickStore.exe).
BTW: Googling for that error message tells me that you are using *Trend Micro* and this wonderful software is reporting this exact error as false positive since 2017 all over the place.
