### ISSUE TITLE
Import orders

### ISSUE THREAD

**Issue by TGS-Bricks** [rgriebl/brickstore#687]
When a customer has placed an order in several batches, the order import seems to have problems. The order on the picture consists of 8 batches, but when choosing the last order listed, I can't import batch 8. And why is the order listed 6 times and not only 1?

<img width="1351" alt="Screenshot 2023-03-11 195802" src="https://user-images.githubusercontent.com/127226598/224506884-2ab6e4af-6026-4ea3-8f75-317d84b3fbcd.png">

**Comment by rgriebl** [comment]
I'm already working on this one. The problem is that the order spans multiple months and BL updates the order date with each new batch, while BrickStore expects the order date to stay constant (date of first batch). I think the date was constant in the past and then something at BrickLink changed recently, but the point is moot ... BrickStore has to learn to deal with this now.
It's far from an easy fix though, because currently the orders are saved into a `year`/`month`/`order-id` directory structure. This has to be replaced with something else, while keeping the existing data.
