### ISSUE TITLE
Crash with Linux-BrickStore-2023.2.1-x86_64.AppImage (works on last version I have)

### ISSUE THREAD

**Issue by user23498723452** [rgriebl/brickstore#689]
Getting an immediate crash upon launch.  I'm not really a user at this time,  but have messed around with it.

My old version (Linux-BrickStore-2022.4.1-x86_64.AppImage) does not crash.   Also confirmed that Linux-BrickStore-2022.11.2-x86_64.AppImage does not crash.

OS Ubuntu 20.04.5 (all updates + latest HWE)

I got a prompt when opening the new version to update BL data.  After that the app seemed to close.  It now doesn't open and merely says the following.

"Failed to load QNetworkInformation's default backend (at /home/runner/work/brickstore/brickstore/src/common/onlinestate.cpp, 27)
Using BrickLink price-guide retriever plugin: "Batched Affiliate API"
Picture cache: 4.0 GB
Loading database: 0s 186ms 211us
Loaded database from /home/username/.cache/BrickStore/database-v8
  Generated at  : 16 Mar 2023 04:01:35 +0000
  ChangeLog I   :     36 504
  ChangeLog C   :          1
  PCCs          :     76 744
  Colors        :        201
  LDraw Colors  :         52
  Item Types    :          8
  Categories    :      1 059
  Items         :    167 944
    Book        :      6 235
    Catalog     :      4 578
    Gear        :     17 042
    Instruction :     11 198
    Minifigure  :     15 172
    Original Box:     18 568
    Part        :     76 585
    Set         :     18 566
UI:
  Device pixel ratio: 1 / Qt::HighDpiScaleFactorRoundingPolicy::PassThrough
  Screen size in pix: 1920 x 1080
  Screen size in mm : 544 x 303
script: Loading scripts from directory: "/home/username/.local/share/BrickStore/extensions"
script:   [ ok ] classic-print-script.bs.qml
Reading ZIP directory: 0s 021ms 077us
ldraw: This ldraw library does not have a brickstore-mapping.cbor file: "mapping file is empty" (at /home/runner/work/brickstore/brickstore/src/ldraw/library.cpp, 331)
Found LDraw at /home/username/.cache/BrickStore/ldraw/complete.zip 
  Last updated: 05 Jun 2022 07:57:11 -0400
Segmentation fault (core dumped)
"

**Comment by rgriebl** [comment]
I can't reproduce this in my 20.04 VM. Could you please run BrickStore via the debugger? It's not perfect, because the AppImage isn't really prepared for debugging, but maybe it could give me a clue:
- open the Terminal app and maximize the window (this makes copying the backtrace later on much easier)
- run `gdb /path/to/brickstore.AppImage`
- if the system complains about "gdb not being found", install it via `sudo apt install gdb`, then retry
- on the first `(gdb)` prompt, type `r` and `Return`
- the next prompt should be right at the crash: type `bt`. Please copy all the lines starting with `#<number>` and paste them here.
Thanks

**Comment by user23498723452** [comment]
This is messed up.  It is just working now.  I have done nothing but try different versions of the app.  lets close this.  It is re-occurs I'll reach out again.
