### ISSUE TITLE
Wrong 'appears in' data

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#701]
Something's going wrong here. The dark orange slope only appears in the 2 shuttle sets not the other 4.

This is with build #988 and a database from earlier today.

![AppearsIn](https://user-images.githubusercontent.com/77812338/230741793-6fdffda0-4582-4006-9576-aeaee39055fc.jpg)

**Comment by rgriebl** [comment]
I'm currently upgrading to a new optimized DB version. Seems like build 988 is loading something wrongly, while the current (not yet pushed) development version works fine.
I'll push a few patches tomorrow that should hopefully fix the problem. I'll ping you when a new build is ready to test.

**Comment by rgriebl** [comment]
Build 992 is ready for testing: https://github.com/rgriebl/brickstore/actions/runs/4648227102
If this one works, it'll release as 2023.4.1 later today

**Comment by SteveTheBrick** [comment]
I just tried build 993 with the database from 6 hours ago. It still has the same problem.

**Comment by rgriebl** [comment]
Could you attach a bsx file that shows the problem? (You probably have to zip it...) I can’t reproduce the error…

**Comment by SteveTheBrick** [comment]
No problem. Here you go..

[temp.zip](https://github.com/rgriebl/brickstore/files/11185171/temp.zip)

**Comment by rgriebl** [comment]
Thanks. Found it! The order is important ... it had the Slope first and the Plate second, but that doesn't trigger it.
The problem is in a few sets like 393-1, that have 2 entries for "Plate 1 x 2" in black: in the case of 393-1, it has an alternate match (id 35) between 15 or 16 of these. My code never expected to see the exact same item id as an alternate, so that's throwing of the algorithm.
I'll have to think about this on how to solve this puzzle...
