### ISSUE TITLE
Problem with dropdown menus on multiple screen setup

### ISSUE THREAD

**Issue by Yomeno** [rgriebl/brickstore#708]
On Mac, version 2023.4.1 build 996 (but previous versions too)

If the main window are in a second or a third screen, all dropdown menus are misplaces or not showing.

**Comment by rgriebl** [comment]
Could this be related to this Qt bug: https://bugreports.qt.io/browse/QTBUG-85968

(as in: are you pinning BrickStore to a specific screen via the Dock menu?)

**Comment by rgriebl** [comment]
Also: which macOS version are you using?

**Comment by Yomeno** [comment]
MacOS 13.3 Ventura
The App is not pinned to a specific screen via the Dock menu.
The bug seems similar of the QT bug. But if I move the main window in an other screen, In the best Case, the dropdown (all !) are misplaced (like 500-600px lower), or just not appear. I presume that they appear but move very quickly outside the screen…

**Comment by rgriebl** [comment]
I can't reproduce it with macOS 13.**2**.1 ... let's see what happens after an update to 13.**3**.1

**Comment by Yomeno** [comment]
Strange, I had this bug for a while now…
<img width="1237" alt="Capture d’écran 2023-04-10 à 18 41 07" src="https://user-images.githubusercontent.com/12167105/230948578-c95d7b14-b38b-4718-b224-ac50c26dbb1f.png">
And once this misplaced menu are appear, no one else can be opened. I have to quit and relaunch the app on the principal screen

**Comment by rgriebl** [comment]
I can reproduce it with 2 screen that do not have the same height (big external, small internal (primary)

If I arrange my 2 screens so that they are aligned at the top edge, the vertical offset of the popups is gone or minimal (there's still something funky going on, as it's off by a few pixels).

If I position the top edge of the primary below the top edge of the external, I get the same crazy vertical offset popups.

I think I'll point my colleagues in the Qt macOS team to this thread and let them sort it out ;)
