### ISSUE TITLE
Issue with "Known colors"

### ISSUE THREAD

**Issue by sorenbruun** [rgriebl/brickstore#778]
I have an issue where the "Known Colors" of an part on BrickStore is different from the same item on BrickLink. 
There seems to be items in BrickStore where the "Known Colors"-list is longer than the same list shown on BrickLink - e.g. 
"32569 Tan Bionicle Mask Akaku" - BrickStore 19 known colors and BrickLink 7 known colors.
"32569 Tan Bionicle Mask Akaku" - BrickStore 14 and BrickLink 9.
"32505 Bionicle Mask Hau" - BrickStore 18 and BrickLink 11.
"64251 Bionicle Fist with Axle Hole - 3 Fingers" - BrickStore 16 and BrickLink 12.
"4597 Cockpit 6 x 6 x 1 1/3 Cabin Base" - BrickStore 11 and BrickLink 5.
"3960pb063  Dish 4 x 4 Inverted (Radar) with Solid Stud with Stripes Pink, Yellow and Green Pattern" - BrickStore ALL THE COLORS and BrickLink NONE.
"44375apb04  Dish 6 x 6 Inverted (Radar) with SW Sith Infiltrator Pattern (Undetermined Type)" - BrickStore ALL THE COLORS and BrickLink NONE.

Running BS version 2023.8.1 (build: 1059) and I love BS. Keep up the excellent work :-)

**Comment by rgriebl** [comment]
BrickStore has no access to the "Known Colors" data on BrickLink. Instead the known colors in BrickStore are compiled from 2 sources: all the part inventories and all the known PCCs (part-color-codes).
If you look at the changelog for 4597 (https://www.bricklink.com/catalogReqList.asp?itemID=1291), you see that all lot of PCCs were added for those "extra" colors that BrickStore is showing. I have no idea why these were added (I guess Lego supplied them), so you'd have to ask the catalog admins / randyf on the BL Forums.

Regarding the none vs. all colors: BrickStore just tries to be helpful here. It knows that there are no known colors, but rather than having you to change the filter from "Known" to "All" in order to select a color, it does so implicitly.

**Comment by rgriebl** [comment]
Closing as this is a BL catalog issue
