### ISSUE TITLE
Brickstore doesn't remember my new password

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#788]
I changed my password after the recent incident. It works ok while Brickstore is running but fails when I exit Brickstore and restart it.

I suspect there is a problem with the exclamation mark in the new password. Try the following:

Enter a password of "!a" in the settings dialog and click ok.
Quit Brickstore and restart it.
The settings dialog shows a password of only 1 character instead of 2.

Win10, build #1086

**Comment by rgriebl** [comment]
Congratulations, you just found a 20 year old bug that's been there since the very first BrickStore version ;)
Passwords are "scrambled" when saved to the registry to protect them at least a little bit. Now that algorithm converts a `!` character to the unicode character value `0xfffe`, This is fine, UNLESS that's the first character in a text string: in this case it has a special meaning (the UTF16 byte-order-mark control character) and it gets removed.
Now I have to find a way to fix this and still be backwards compatible...

**Comment by SteveTheBrick** [comment]
That's great! I must be the first ever Brickstore user to have a password starting with "!". I'm sure you'll find a solution - I can always change my password in the meantime.
