### ISSUE TITLE
BrickLink inventory import error

### ISSUE THREAD

**Issue by ChristianGrieger** [rgriebl/brickstore#791]
**Describe the bug**
I try to download my inventory from Bricklink but i get the error about missmatch of user or password. I use the login with success on the store itself and also with Brickpacker.

**To Reproduce**
1. Go to File -> Import
2. Click on 'BrickLink Shop Inventory
3. See error

**Expected behavior**
Download the current inventory.

**Screenshots**
<img width="1034" alt="Bildschirmfoto 2023-11-13 um 18 30 12" src="https://github.com/rgriebl/brickstore/assets/8712219/aa00af2b-60ba-4000-b035-2e631b100171">

**System information**
MacBook Pro - macOS 14.0 (23A344)

**Comment by rgriebl** [comment]
There could be 2 problems:
1) you entered a password longer than 15 characters resetting your password in BL (which shouldn't work, but does: see #787)
2) your password starts with an `!` and you are running into #788 
In both cases, you need to change your password to 15 characters or less, not starting with an `!`
At least number 2 is going to be fixed in tonight's upcoming BrickStore update.

**Comment by ChristianGrieger** [comment]
That was easy :) thank you!
