### ISSUE TITLE
Standard Print Template 

### ISSUE THREAD

**Issue by GreatBrickLab** [rgriebl/brickstore#81]
Will this get a folder like brickstock for the standard print template?   I created a modified template that we use for hand verification of our inventory by drawer (remarks).

[picklist_Copy1.qs.txt](https://github.com/rgriebl/brickstore/files/5803401/picklist_Copy1.qs.txt)

**Comment by BrickSouth** [comment]
It would be great to get a better print template. I've never been able to figure out how to add remarks or comments to it. When I print the only columns I get are image, Cond., Part, Lots, Qty, Price and Total. I've tried messing with the template file, but it doesn't ever change anything. I wonder if it could be set up to just print whatever columns you have currently set up in a file.

**Comment by GreatBrickLab** [comment]
BrickSouth,  I have a template that works for BrickStock. The file is in
this thread on github

**Comment by BrickSouth** [comment]
Yeah I saw that...I tried copying and pasting the contents into the “Standard” file in the BrickStock print-template folder, but that didn’t work. I guess I need to create a new file?

**Comment by paramecie** [comment]
I wouldn't touch the standard one...

We use also a special one, we simply copied from standard.qs and renamed if (as a .qs file)
Then you can edit it (Notepad++)

This was with both the first BrickStore and BrickStock - I didn't test this with the current one, though...

**Comment by BrickSouth** [comment]
Ok, I did not know about removing the txt extension, that worked, thanks! I still feel like this print thing could be more user friendly though.

**Comment by BrickSouth** [comment]
So I thought about starting a new issue about printing since the latest update added a new print feature, but I see this one is still open and is still applicable so I will just add on to this...

I like where the new printing thing is going with being able to modify which columns you want, but the template GreatBrickLab provided here is still better. I like how it is formatted with the important text being larger font (drawer number and BIN number) and the ability to use paper saving to put 2 sheets on 1 piece of paper is nice too. So for now, I guess I will keep using the customized print script.

I see in the release notes it says, "**The old print script (as well as any customized print scripts) are still available via the
Extras menu.** Does anyone know where you put customized print scripts? There doesn't seem to be a folder for Brickstore like there is for Brickstock to drop the .qs file into. I've been having to use Brickstock still for printing, but would be great if I could get the same custom print out of Brickstore.

**Comment by rgriebl** [comment]
I've ported the script from @GreatBrickLab (attached above) to the new scripting engine and added it as an example in the git repo.
There's also a new port of my BL shop's invoice generator, plus a README telling you where things need to go for BrickStore to pick them up:
https://github.com/rgriebl/brickstore/tree/master/extensions

And yes -- a general documentation for the scripting API is still missing ;)

**Comment by GreatBrickLab** [comment]
This is great!   My set builder (Steve) uses the printout with remarks to
shop the store and our back warehouse to build sets all the time.  He will
faster now that the printing is done.

Thanks you so much
Chris
GBL

**Comment by rgriebl** [comment]
@GreatBrickLab I ported the wrong script (Sylvains example) instead of you picklist. This is fixed now in #342
