### ISSUE TITLE
Brickstore database update time out

### ISSUE THREAD

**Issue by wiaone87** [rgriebl/brickstore#813]
There is problem with database update, with new version of application.

![image](https://github.com/rgriebl/brickstore/assets/156841581/82a980ce-d9a2-4833-9b38-70b8eb7de810)

### BrickStore 2024.1.2 (build: 1143)

* **brickstore.ldraw**: 15 Oct 2023 09:19:54 +0200
* **brickstore.locale**: pl
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930153)
* **build.date**: 2024-01-11T21:19:23.000
* **build.host**: fv-az662-930
* **build.number**: 1143
* **build.qt.version**: 6.6.1
* **hw.cpu**: AMD Ryzen 9 3900X 12-Core Processor
* **hw.cpu.arch**: x86_64
* **hw.gpu**: NVIDIA GeForce RTX 4070
* **hw.gpu.arch**: nvidia
* **hw.memory.gb**: 31.9
* **os.arch**: x86_64
* **os.productname**: Windows 11 Version 22H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.6.1
* **windows.tabletmode**: false

**Comment by wheeliegal** [comment]
this is so upsetting I can't use BrickStore since the new update.

**Comment by rgriebl** [comment]
UPDATE: Just had a call with the datacenter support: the general routing problem on their side was fixed hours ago, but somehow my server instance still has problems. They are working on it now.

**Comment by wouterslager** [comment]
Thanks for the update, I just encountered this in the app as well

**Comment by Jeremy-Back2BackBrix** [comment]
I'm having the same problem with my Brickstore, I updated it yesterday and it worked fine but today its saying  "Socket operation timed out"

**Comment by froqzy** [comment]
While there's obviously not much that can be done about server issues outside Brickstore, it might be possible to make Brickstore less dependent on having a connection. Currently, the main issue is that after a Brickstore update it apparently needs a fresh database download otherwise Brickstore doesn't function. Possible solution: store the old database locally during the update process, so that Brickstore will always work after updating, even if Bricklink or its servers are down.

**Comment by froqzy** [comment]
At the risk of going off topic: in general I think that it would be best if Brickstore is able to work offline and use all data from the last available download. This does not just concern the database update, but at least also the "Import Bricklink Order". Each time Brickstore starts up it needs the Bricklink password to access it and if Bricklink either there is something wrong with the password or if Bricklink is down you're not able to access the Order overview. At least if I'm not missing something ;-)

**Comment by rgriebl** [comment]
The tagline for BrickStore is `An offline BrickLink inventory management tool.` and that's exactly what it does.

1. BrickStore only needs a DB update when the DB format changes. Unfortunately that's exactly what happened between 2023.11.2 and 2024.1.2. (just for reference: the DB format changed 10 times during the last 20 years). Reading the old database is not possible, as there is vital information missing.

2. The BrickLink orders are NOT updated every time you start BrickStore. Everything is stored in an SQL database for later (offline) retrieval. The order list is only updated when you click the update button, OR when BrickStore hasn't retrieved any orders yet and you open the import order dialog.

3. Even when an update fails, all order data is available offline. This has been like that since forever.

**Comment by froqzy** [comment]
Thanks for clarifying, and for all your efforts in general - you've made an amazing LEGO inventory tool!

Only point 2 (which is off topic - sorry) is not clear to me: every time I open Brickstore and click the Import / Bricklink Order button it asks for a password. So, without password I cannot access the orders, or am I missing something? I was also under the impression that because of the password request it also initiates a download or is the password request processed offline and if so, why is that needed?

Thanks again!

**Comment by rgriebl** [comment]
Now I got your (off topic) point: fixed in 6a97e7d

**Comment by rgriebl** [comment]
UPDATE regarding the DB download: the datacenter guys were hopeful to get it fixed until this evening (CET), but it's (obviously) still not working. Let's hope they get to it tomorrow morning...

**Comment by froqzy** [comment]
Awesome work and thanks for the updates!
