### ISSUE TITLE
brickstore version 2024.2.1 could not load the new database

### ISSUE THREAD

**Issue by lilyximsu** [rgriebl/brickstore#846]
**Describe the bug**
A clear description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information**
Please tell us which system you are running on and which BrickStore version you are using.
In BrickStore, just open `Help` > `System information...`, Click `Copy to clipboard` and then paste  here.

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by lilyximsu** [comment]
![1709857913(1)](https://github.com/rgriebl/brickstore/assets/161108465/e6b4c9ec-1381-4042-b62d-67113d355755)


it said: could not load the new database.  Download nad decompress failed: the cridential wer not recognized/invlaid arugument.  version 2.24.2.1

**Comment by rgriebl** [comment]
@Silverbul your problem is unrelated. I just forgot that Android and iOS users get access to unreleased versions. Just update BrickStore again.

@lilyximsu your problem is strange. The error message comes from the depths of Windows and tells me (according to Microsoft documentation) that Windows found a problem with client side HTTPS certificates... but BrickStore doesn't use client side HTTPS certificates at all!
Could you disable your Firewall/Antivirus and try again?

**Comment by Silverbul** [comment]
Yepp. It works.

**Comment by xaraxarax** [comment]
Gleiches hier nach Upgrade von 2023.8.1 auf 2024.4.1

Datenbank aktualisieren
![grafik](https://github.com/rgriebl/brickstore/assets/79638214/efb60f72-45d0-4a80-aa8b-e4b0b401d88f)

LDraw Download
![grafik](https://github.com/rgriebl/brickstore/assets/79638214/c6a116e5-e89c-46c4-b426-f0c7d0ede852)

Download Shopbestand
![grafik](https://github.com/rgriebl/brickstore/assets/79638214/7d328b53-3246-4252-adc3-ce640f5e35af)

**Comment by rgriebl** [comment]
@xaraxarax Irgendwas hängt da in Windows quer: Könntest du bitte etwas im Explorer nachschauen: welche Dateien sind bei Dir im Ordner `C:\Programme\BrickStore\tls` ?

**Comment by rgriebl** [comment]
Bitte auch Hilfe -> Systeminformationen kopieren und hier pasten

**Comment by xaraxarax** [comment]
Das ist da drin

![grafik](https://github.com/rgriebl/brickstore/assets/79638214/81156845-a1fb-45c8-b76b-56205228b8a2)

Bis Version 2023.11.2 funktioniert es. Die anderen 2024.x habe ich nicht getestet, wegen dem Priceguide Problem.

**Comment by rgriebl** [comment]
Es kann sein, dass dein Windows 10 zu alt ist, deswegen brauche ich die System Infos

**Comment by xaraxarax** [comment]
Ist eine RDS auf Basis 2016 Server LTSB EOS 01.2017. Ist aber nicht kritisch, ich nehme erstmal die 2023.11.2. Vielleicht fällt dir dazu mal irgendwas ein.

BrickStore 2023.11.2 (build: 1093)
brickstore.ldraw: 16 Apr 2024 12:58:42 +0200
brickstore.locale: de
build.arch: x86_64
build.compiler: Microsoft Visual-C++2019 (192930152)
build.date: 2023-11-14T02:11:09.000
build.host: fv-az1457-229
build.number: 1093
build.qt.version: 6.5.2
hw.cpu: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
hw.cpu.arch: x86_64
hw.gpu: Microsoft Basic Render Driver
hw.gpu.arch: ?
hw.memory.gb: 32.0
os.arch: x86_64
os.productname: Windows Server 2016 Version 1607
qt.debug: false
qt.platformname: windows
qt.version: 6.5.2
windows.tabletmode: false

**Comment by rgriebl** [comment]
Das ist aus der Steinzeit. BrickStore braucht mindestens Windows 10 1809. Die 2023er Versionen funktionieren nur zufällig auf deinem System, weil lange veralteter Code für unsichere SSL Verbindungen in Qt 6.5 noch aktiv war. Das wurde mit Qt 6.6 behoben und TLS 1.3 forciert. Damit kommt allerdings dein Windows Server von 2016 nicht klar.

Also: entweder eine alte BrickStore Version benutzen und mit potentiell unsicheren TLS 1.2 Verbindungen leben. Oder auf eine aktuelle Windows Version umsteigen die das aktuelle TLS 1.3 unterstützt.

**Comment by rgriebl** [comment]
ENGLISH: BrickStore needs at least Windows 10, release 1809 to properly support secure SSL connections according to the TLS 1.3 standard. Older Windows (Server) versions cannot support that and will throw this weird error instead.
BrickStore versions before 2024 do work, because TLS 1.2 support was still enabled in the Qt base library, although it shouldn't have been for security reasons.

Either you keep using old 2023.x BrickStore versions or you update your Windows to a version that supports TLS 1.3
