### ISSUE TITLE
App crashes on Android 14.0  after scrolling on a list

### ISSUE THREAD

**Issue by habex-ch** [rgriebl/brickstore#865]
**Describe the bug**
App still crashes with 2024.4.1.1217 but later than before (issue #848).
App crashes as soon as scroll to the an open list.

I also can not select select the default currency anymore, there only is en empty dropdown.

**To Reproduce**

1. `Bricklink Set Inventory` -> `Agents` -> `8637-1` -> `Import`.
2. Scrolling
3. App crashes

**Expected behavior**
No crashes

**System information**
* Android 14.0
* Brickstore 2024.4.1.1217
* ![image](https://github.com/rgriebl/brickstore/assets/34911987/e7fb1777-fecb-4ad0-b567-a8dd5d775000)

**Comment by mmally** [comment]
Same for me. As soon as I scroll in any direction the app crashes.

**Comment by rgriebl** [comment]
Yep - I see this in the sentry reports. Seems like this problem is not limited to the tables cells drawing (that's what I worked around), but a general problem in the Qt base library (that BrickStore is built upon) when accessibility options are enabled in Android 14.
This is a new problem that nobody has reported before. I'm currently discussing this with my colleagues at Qt, but this might take some time to figure out what is going wrong and how to fix it right.
