### ISSUE TITLE
NO 3D option in Info WIndow

### ISSUE THREAD

**Issue by Broberick** [rgriebl/brickstore#914]
Hello,
there is no "3D" option in the Info-Window.
Any Ideas?
Regards

![no-3d-option-in-info-window](https://github.com/user-attachments/assets/ff14063f-992d-4229-af1b-fb6fbb7fbd03)

**Comment by rgriebl** [comment]
This means that your graphics card is blacklisted, either because it is so old that is does not support all the features needed for BrickStore's 3D renderer, or the drivers are known to be buggy and tend to crash.
See here for the current blacklist: https://github.com/rgriebl/brickstore/blob/main/src/ldraw/renderwidget.cpp#L25
