### ISSUE TITLE
Cannot install on Linux Mint

### ISSUE THREAD

**Issue by ericools** [rgriebl/brickstore#920]
**Describe the bug**  App Image Issue
/tmp/.mount_Linux-jFnmkt/AppRun.wrapped: error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory

**To Reproduce**
./Linux-AppImage-BrickStore*.AppImage

**Expected behavior**
Runs program 

**System information**
Linux Mint 19.3 MATE 64bit
Brickstore 5.2-x86_64
Hardware: Udoo Bolt

---------
**Describe the bug**  Deb Issue
Reading package lists... Done
E: Unsupported file ./Downloads/Ubuntu-22.04-brickstore_2024.5.2_amd64.deb given on commandline

**To Reproduce**
sudo apt install ./Downloads/Ubuntu-22.04-brickstore_2024.5.2_amd64.deb

**Expected behavior**
Installs program 

**System information**
Linux Mint 19.3 MATE 64bit
Brickstore 5.2-x86_64
Hardware: Udoo Bolt

**Comment by rgriebl** [comment]
Sorry, but Mint 19.3 is just too old. It's 5 years old by now and out of support since 2023. 
The AppImage is missing 3D support from the OS and the deb package is already in a newer format that your distro doesn't even recognize as such.

The bare minimum for the AppImage is Ubuntu 20.04 (or equivalent) and 22.04 for the DEB.

If your system supports Flatpak, then you might get lucky though: the next release will come as Flatpak as well. No guarantees that this will work on your old Mint distro.

You can already download the current preview version here: https://github.com/rgriebl/brickstore/actions/runs/11246994122
(you need to be logged into GitHub, then scroll down to Linux - Flatpak)
